name: Bug Report
description: 
title: "[Bug]"
labels: bug
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to report a bug!
      First, please understand this repo is called deck.gl-community because it is maintained by the community,
      (there are no dedicated maintainers) meaning that we mostly rely on people who report bugs to make PRs for the fixes.
      We are however happy to help review and land your PRs, and publish new versions with the fixes.
      In order to prevent drowning in unactionable bugs, maintainers will ruthlessly close any bugs that are not clearly defined. 
      In particular, if you are having general issues with your particular build environment, 
      please start a conversation in [Discussions](https://github.com/visgl/deck.gl/discussions)
      rather than opening issues.
      Also check [existing issues](https://github.com/visgl/deck.gl-community/issues)to avoid filing duplicate bugs.
      You may find answers faster by searching in [the documentation](https://deck.gl-community/search).
- type: checkboxes
  id: flavor
  attributes:
    label: Module
    description: First, we need to understand which deck.gl-community module you are using.
    options:
      - label: deck.gl-community/arrow-layers
      - label: deck.gl-community/bing-maps
      - label: deck.gl-community/editable-layers
      - label: deck.gl-community/experimental
      - label: deck.gl-community/graph-layers
      - label: deck.gl-community/layers
      - label: deck.gl-community/react
      - label: deck.gl-community/react-graph-layer
- type: textarea
  attributes:
    label: Description
    description: What you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: What you expect to see.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: |
      Providing the following could help us understand this issue faster:
        - A Codepen that reproduces the behavior. A good starting point is the "edit in CodePen" links in the layer documentations.
        - A sample of your dataset
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      Example:
        - **Framework version**: @9.0.0
        - **Browser**: Chrome 120.0
        - **OS**: Windows 11
    value: |
        - Framework version:
        - Browser:
        - OS:
  validations:
    required: true
- type: textarea
  attributes:
    label: Logs
    description: Check the browser console for any relevant errors or warnings.
  validations:
    required: false
