# Project Information
site_name: 'deck.gl-raster'
site_description: 'Deck.gl layers and WebGL modules for client-side satellite imagery processing'
site_author: 'Kyle Barron'

docs_dir: 'docs'
site_dir: 'build'

# Repository
repo_name: 'kylebarron/deck.gl-raster'
repo_url: 'https://github.com/kylebarron/deck.gl-raster'
edit_uri: 'blob/master/docs/src/'
site_url: 'https://kylebarron.dev/deck.gl-raster/'

# Social links
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/kylebarron'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/kylebarron2'

# Layout
nav:
  - Home: 'index.md'
  - Overview:
    - Use Cases: 'overview/use-cases.md'
    - Loading Data: 'overview/loading-data.md'
  - Install: 'get-started.md'
  - Examples:
      - RasterLayer: 'examples/raster-layer-md.md'
      - RasterMeshLayer: 'examples/raster-mesh-layer-md.md'
  - API:
      - deck.gl Layers:
          - RasterLayer: 'layers/raster-layer.md'
          - RasterMeshLayer: 'layers/raster-mesh-layer.md'
      - WebGL Modules:
          - Overview: 'webgl-modules/overview.md'
          - Create Image: 'webgl-modules/create-image.md'
          - Alter Image:
              - Color: 'webgl-modules/color.md'
              - Pansharpen: 'webgl-modules/pansharpen.md'
              - Spectral Indices: 'webgl-modules/spectral-indices.md'
              - Custom Modules: 'webgl-modules/custom-modules.md'
  - Colormaps: 'colormaps.md'

# Theme
theme:
  icon:
    logo: 'fontawesome/solid/globe-americas'
    repo: 'fontawesome/brands/github'
  name: 'material'
  language: 'en'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Nunito Sans'
    code: 'Fira Code'

# Uncomment if I use math in the docs in the future
# extra_javascript:
#     - helpers/helpers.js
#     - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# These extensions are chosen to be a superset of Pandoc's Markdown.
# This way, I can write in Pandoc's Markdown and have it be supported here.
# https://pandoc.org/MANUAL.html
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
