name: website

on:
  push:
    branches:
      - master
      - '*-release'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-26.04

    if: ${{ github.repository_owner == 'visgl' }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'

      - name: Enable Corepack
        run: corepack enable yarn

      - name: Install root workspace dependencies
        run: yarn install --immutable
        env:
          YARN_ENABLE_HARDENED_MODE: 0

      - name: Install website dependencies
        run: cd website && yarn install --immutable
        env:
          YARN_ENABLE_HARDENED_MODE: 0

      - name: Configure Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Build website
        env:
          MapboxAccessToken: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          GoogleMapsAPIKey: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          GoogleMapsMapId: ${{ secrets.GOOGLE_MAPS_MAP_ID }}
        run: cd website && yarn build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: website/build

  deploy:
    needs: build
    runs-on: ubuntu-26.04

    if: ${{ github.repository_owner == 'visgl' }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
